import { BlogPost, Volunteer, Event, Category, GalleryImage, TeamMember, Contact } from './types';

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Our Annual Charity Gala was a Success!',
    author: 'Jane Doe',
    date: '2023-10-28',
    status: 'Published',
  },
  {
    id: '2',
    title: 'New Volunteer Opportunities This Fall',
    author: 'John Smith',
    date: '2023-09-15',
    status: 'Published',
  },
  {
    id: '3',
    title: 'Recap: Community Clean-Up Day',
    author: 'Jane Doe',
    date: '2023-08-05',
    status: 'Published',
  },
  {
    id: '4',
    title: 'Upcoming Workshop: Grant Writing Basics',
    author: 'Admin',
    date: '2023-11-01',
    status: 'Draft',
  },
];

export const volunteers: Volunteer[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    phone: '123-456-7890',
    joined: '2022-03-12',
    avatarUrl: 'https://picsum.photos/seed/v1/40/40',
  },
  {
    id: '2',
    name: 'Bob Williams',
    email: 'bob@example.com',
    phone: '234-567-8901',
    joined: '2021-07-22',
    avatarUrl: 'https://picsum.photos/seed/v2/40/40',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    phone: '345-678-9012',
    joined: '2023-01-05',
    avatarUrl: 'https://picsum.photos/seed/v3/40/40',
  },
  {
    id: '4',
    name: 'Diana Prince',
    email: 'diana@example.com',
    phone: '456-789-0123',
    joined: '2022-11-30',
    avatarUrl: 'https://picsum.photos/seed/v4/40/40',
  },
];

export const events: Event[] = [
  {
    id: '1',
    name: 'Annual Charity Gala',
    date: '2023-10-27',
    location: 'Grand Ballroom',
    attendees: 250,
  },
  {
    id: '2',
    name: 'Tech for Good Workshop',
    date: '2023-11-15',
    location: 'Online',
    attendees: 120,
  },
  {
    id: '3',
    name: 'Food Drive',
    date: '2023-12-01',
    location: 'Community Center',
    attendees: 75,
  },
  {
    id: '4',
    name: 'Holiday Toy Drive',
    date: '2023-12-18',
    location: 'City Hall',
    attendees: 0,
  },
];

export const contacts: Contact[] = [
  {
    id: '1',
    name: 'Emily Carter',
    email: 'emily.c@example.com',
    message:
      'Hello, I am a software developer with an interest in educational outreach. Are there any opportunities where I can use my technical skills to help teach kids about coding?',
    date: '2023-10-20',
    status: 'Contacted',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'm.chen@example.com',
    message:
      "I'm passionate about the environment and would love to get involved in any local conservation or clean-up events you have planned.",
    date: '2023-10-18',
    status: 'Not Contacted',
  },
  {
    id: '3',
    name: 'Sarah Rodriguez',
    email: 'sarah.r@example.com',
    message:
      "I have a background in event planning and logistics. I'd be happy to help organize or manage any upcoming fundraising events.",
    date: '2023-10-15',
    status: 'Contacted',
  },
  {
    id: '4',
    name: 'David Lee',
    email: 'david.lee@example.com',
    message:
      "I enjoy working with animals and would like to volunteer at a shelter or with animal rescue operations. Please let me know if you have any programs like that.",
    date: '2023-10-12',
    status: 'Not Contacted',
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Sanjeev Kumar',
    email: 'sanjeev@example.com',
    phone: '123-456-7890',
    joined: '2022-03-12',
    avatarUrl: 'https://picsum.photos/seed/v1/100/100',
    role: 'Coordinator',
    type: 'Asset',
  },
  {
    id: '2',
    name: 'Sandeep Kumar',
    email: 'sandeep@example.com',
    phone: '234-567-8901',
    joined: '2021-07-22',
    avatarUrl: 'https://picsum.photos/seed/v2/100/100',
    role: 'Coordinator',
    type: 'Asset',
  },
  {
    id: '3',
    name: 'Manish Kumar',
    email: 'manish@example.com',
    phone: '345-678-9012',
    joined: '2023-01-05',
    avatarUrl: 'https://picsum.photos/seed/v3/100/100',
    role: 'Coordinator',
    type: 'Asset',
  },
  {
    id: '4',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '456-789-0123',
    joined: '2022-11-30',
    avatarUrl: 'https://picsum.photos/seed/v4/100/100',
    role: 'Lead Volunteer',
    type: 'Asset',
  },
  {
    id: '5',
    name: 'Vikram Singh',
    email: 'vikram@example.com',
    phone: '567-890-1234',
    joined: '2023-02-15',
    avatarUrl: 'https://picsum.photos/seed/v5/100/100',
    role: 'Field Coordinator',
    type: 'Asset',
  },
  {
    id: '6',
    name: 'Rajesh Verma',
    email: 'rajesh@example.com',
    phone: '678-901-2345',
    joined: '2023-03-20',
    avatarUrl: 'https://picsum.photos/seed/v6/100/100',
    role: 'Volunteer',
    type: 'Asset',
  },
  {
    id: '7',
    name: 'Anjali Mehta',
    email: 'anjali@example.com',
    phone: '789-012-3456',
    joined: '2023-04-10',
    avatarUrl: 'https://picsum.photos/seed/v7/100/100',
    role: 'Volunteer',
    type: 'Asset',
  },
  {
    id: '8',
    name: 'Sanjeev Kumar',
    email: 'sanjeev.km@example.com',
    phone: '111-222-3333',
    joined: '2022-03-12',
    avatarUrl: 'https://picsum.photos/seed/v8/100/100',
    role: 'Coordinator',
    type: 'Key Member',
  },
  {
    id: '9',
    name: 'Sandeep Kumar',
    email: 'sandeep.km@example.com',
    phone: '222-333-4444',
    joined: '2021-07-22',
    avatarUrl: 'https://picsum.photos/seed/v9/100/100',
    role: 'Coordinator',
    type: 'Key Member',
  },
  {
    id: '10',
    name: 'Manish Kumar',
    email: 'manish.km@example.com',
    phone: '333-444-5555',
    joined: '2023-01-05',
    avatarUrl: 'https://picsum.photos/seed/v10/100/100',
    role: 'Coordinator',
    type: 'Key Member',
  },
  {
    id: '11',
    name: 'Priya Sharma',
    email: 'priya.s@example.com',
    phone: '444-555-6666',
    joined: '2022-11-30',
    avatarUrl: 'https://picsum.photos/seed/v11/100/100',
    role: 'Lead Volunteer',
    type: 'Key Member',
  },
  {
    id: '12',
    name: 'Vikram Singh',
    email: 'vikram.s@example.com',
    phone: '555-666-7777',
    joined: '2023-02-15',
    avatarUrl: 'https://picsum.photos/seed/v12/100/100',
    role: 'Field Coordinator',
    type: 'Key Member',
  },
  {
    id: '13',
    name: 'Rajesh Verma',
    email: 'rajesh.v@example.com',
    phone: '666-777-8888',
    joined: '2023-03-20',
    avatarUrl: 'https://picsum.photos/seed/v13/100/100',
    role: 'Volunteer',
    type: 'Key Member',
  },
  {
    id: '14',
    name: 'Anjali Mehta',
    email: 'anjali.m@example.com',
    phone: '777-888-9999',
    joined: '2023-04-10',
    avatarUrl: 'https://picsum.photos/seed/v14/100/100',
    role: 'Volunteer',
    type: 'Key Member',
  },
];